CREATE TABLE news(id INT(4) PRIMARY KEY NOT NULL AUTO_INCREMENT, name VARCHAR(100), description VARCHAR(500), is_active VARCHAR(1), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, author_id INT(4));

